### ISSUE TITLE
Setting device out values doesn't work always

### ISSUE THREAD

**Issue by rikki78** [circuitdb/pimatic-node-red#10]
Hello,
I need your support again. I'm not sure if it is caused by node-red or the MySensors plugin but the last couple of days I have some issues with the device out node. 

Sometimes (yes, not always) when setting a device out node to a value (with parameter), the value isn't set in the actual device. The device stays the same value on the front-end. This used to work fine before. 

What can I do to provide some useful debug info?

**Comment by joshendriks** [comment]
Hmmm, Can you provide the configs and your logs? Unfortunately I do not have MySensors

**Comment by rikki78** [comment]
Well the config is quite large and in the logs I can't see any errors. Is there a separate node-red log? 
I've tried replicating the error again tomorrow but without success (fortunately). I think it is not node-red related. Did you change something in this part recently?
It could also be related to the connection or the Mysensors plugin.

**Comment by joshendriks** [comment]
Nope, no changes recently. Except for solving Issue #9, which is NOT related to the device out node.

**Comment by rikki78** [comment]
I think this has todo with a change in the MySensors plugin, though I'm not sure yet. 
In the plugin there is now a check on the value being between 0 and 100 which wasn't in before.

What I do notice is the type I use to inject values, matter. So if I inject a string 0 the dimmer will go to 0. If I inject the number 0 the dimmer goes to its max 100.
Injecting 50 as string and 50 as number doesn't make a difference.

Which type should be used in the payload?
