### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by rikki78** [circuitdb/pimatic-node-red#11]
Hi,
I get an assertion error when setting a dummy presence device to false. When setting it again to false I don't get the error.
The error is
"AssertionError: state is 'event' or state is true or state is false"

**Comment by joshendriks** [comment]
I cannot reproduce. Can you provide some screenshots of you configuration?

**Comment by rikki78** [comment]
I've used this flow. When injecting true and then false it goes into the error. The strange thing is for some presence devices I don't get this error. 

[{"id":"f719549d.894238","type":"device out","z":"526c0929.103db8","device":"rik-samsung","action":"changePresenceTo","parameter":"","x":1364.8665771484375,"y":152.46661376953125,"wires":[]},{"id":"fc88ed5e.8e0ab","type":"change","z":"526c0929.103db8","name":"","rules":[{"t":"set","p":"parameter","pt":"msg","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":983,"y":272,"wires":[["f719549d.894238","cad8651a.151a78"]]},{"id":"e2e9fe9.b8db1","type":"inject","z":"526c0929.103db8","name":"","topic":"","payload":"false","payloadType":"bool","repeat":"","crontab":"","once":false,"x":790,"y":252,"wires":[["fc88ed5e.8e0ab"]]},{"id":"dcff804d.a8654","type":"inject","z":"526c0929.103db8","name":"","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"x":799,"y":299.3333435058594,"wires":[["fc88ed5e.8e0ab"]]},{"id":"cad8651a.151a78","type":"debug","z":"526c0929.103db8","name":"","active":true,"console":"false","complete":"true","x":1285,"y":268,"wires":[]}]

**Comment by joshendriks** [comment]
I created a DummyPresence device called "rik-samsung" and used your flow. Unfortunately I was not able to reproduce this on my system.....

**Comment by rikki78** [comment]
Thanks for your help. I have deleted the devices from pimatic and created new ones (with new names). Now it is working ok. So nothing node-red related it seems.
