### ISSUE TITLE
Update 1.0.2 does not install in pimatic

### ISSUE THREAD

**Issue by AvdH** [circuitdb/pimatic-node-red#12]
Updating node-red in pymatic gives the error
    error [pimatic]: Error running "./node_modules/pimatic/ppm.js install pimatic-node-red@1.0.2 --unsafe-perm"

Removing the pimatic-node-red folder from the node_modules folder  and restarting pimatic does not fix the problem.

**Comment by JosHendriksRHM** [comment]
I need a bit more information.

- Do you have a log file?
- From which version were you trying to update?
- I assume you are using the update function using the pimatic web UI?

**Comment by joshendriks** [comment]
I need a bit more information.
- Do you have a log file?
- From which version were you trying to update?
- I assume you are using the update function using the pimatic web UI?

**Comment by AvdH** [comment]
Hi Jos
Yes I'm using the update function from pimatic. From 1.0.1 to 1.0.2
I added the log file (renamed to txt because of upload ;-)

By the way, I had the same issues with the previous verion. But because I did a complete re-install of pimatic (for other reasons) the problem resolved itself.


[npm-debug.log.txt](https://github.com/joshendriks/pimatic-node-red/files/1099597/npm-debug.log.txt)

**Comment by joshendriks** [comment]
Solved in 1.0.3. See also: https://forum.pimatic.org/topic/2085/node-red-for-pimatic-available/17

**Comment by AvdH** [comment]
Hi Jos
Update workes OK now.
Thanks
