### ISSUE TITLE
Error during starting

### ISSUE THREAD

**Issue by rikki78** [circuitdb/pimatic-node-red#13]
Hi again

I see this error when starting

29 Jun 16:09:04 - [warn] [XML] Error: Cannot find module './_assignValue'
29 Jun 16:09:04 - [warn] ------------------------------------------------------
29 Jun 16:09:04 - [info] User directory : /home/pi/pimatic-app/node_modules/pimatic-node-red/../../

Is it something to worry about?

**Comment by joshendriks** [comment]
Do you have any additional node-red plugins installed?

**Comment by rikki78** [comment]
Yes. Owntracks, geofence, node-google, bigtimer, dashboard. So I guess you asked this because it can be one of these as well?

**Comment by JosHendriksRHM** [comment]
Can be anything. Are you able to do some tests? MAybe uninstalling those node-red plugins one-by-one to if if the warning is triggered by one of those? From there on we dive into it.

**Comment by joshendriks** [comment]
Can be anything. Are you able to do some tests? MAybe uninstalling those node-red plugins one-by-one to if if the warning is triggered by one of those? From there on we dive into it.

**Comment by rikki78** [comment]
I don't think it is a big thing so I will close the issue.
