### ISSUE TITLE
Improve readability and creating flows

### ISSUE THREAD

**Issue by rikki78** [circuitdb/pimatic-node-red#2]
First of all thanks for this nice plugin! I’ve started to play with it and I think it could simplify and speed up some rules from pimatic. Would it be possible to have the variable name and a unique topic in each input block? That would improve readability and creating flows.

Second is how can I send parameters to a device? eg changeDimlevelTo needs a parameter to be included.

**Comment by rikki78** [comment]
@Jospfh could you help perhaps?

**Comment by circuitdb** [comment]
I would be happy to improve this thing!

Can you please clarify what you mean with the variable name and unique topic? Do you want the variablename in msg.topic?

Are you using the latest version from npm? The latest version display the the varibale name in the node.
![image](https://cloud.githubusercontent.com/assets/12962931/18310661/08844418-7500-11e6-9ff4-9fea16b482cd.png)

Currently parameters are not supported. I have created  #3 for this.

**Comment by rikki78** [comment]
Yes that is exactly what I meant!
If the message would have the variable name in the topic it would help a lot I think. I will update the plugin tonight. Can I just use the update function in pimatic?

**Comment by circuitdb** [comment]
Ok, I will add the name to the topic.

As for the update I am not sure. I think it will work. 'npm update pimatic-node-red' will work for sure. Please note that I had to reinstall all my noder-red plugins (like node-red-node-pushbullet) afterwards .....

**Comment by rikki78** [comment]
I was able to update through the pimatic update function. The name of the variable is indeed displayed

**Comment by circuitdb** [comment]
The variable name is now passed along in msg.variable
