### ISSUE TITLE
Node device out cannot yet execute actions that require a parameter.

### ISSUE THREAD

**Issue by circuitdb** [circuitdb/pimatic-node-red#3]
Node device out cannot yet execute actions that require a parameter. eg changeDimlevelTo is not supported.

**Comment by rikki78** [comment]
Any progress on this? I'm now using a work around by sending a MQTT message, which then activates the function. Leaving this step out could make it faster and easier.

This plugin is really very nice, it makes it much easier to implement more complex rules and re-usability is much better as well.

**Comment by circuitdb** [comment]
Thanks for the reminder! I have been working on it now and it is almost done. To keep things simple it only allows a single parameter. Would that be sufficient for now?

**Comment by circuitdb** [comment]
This is what I currently have. The parameter can be specified by setting msg.parameter of by setting a fixed value in config.

![image](https://cloud.githubusercontent.com/assets/12962931/19576431/46fc11f0-9713-11e6-9e99-944b7a0c8d71.png)

**Comment by rikki78** [comment]
Nice!
For me a single parameter is enough (for now ;-))
Let me know if you need help with testing!

**Comment by circuitdb** [comment]
I just uploaded version 0.0.6!

**Comment by rikki78** [comment]
Great! I'll try to test it this weekend.
Op zo 23 okt. 2016 om 22:22 schreef circuitdb notifications@github.com

**Comment by rikki78** [comment]
Thanks for the update, I've tested it and works great!

**Comment by circuitdb** [comment]
Good to hear!
