### ISSUE TITLE
Cannot find module 'i18next-client'

### ISSUE THREAD

**Issue by thost96** [circuitdb/pimatic-node-red#4]
Hi,

after installing pimatic-node-red the webserver under `<pimatic-ip>:8000/red` is not working and i get this error message: `Cannot find module 'i18next-client'`.

**Comment by circuitdb** [comment]
Can you post your pimatic logging? e.g. pimatic-daemon.log in case you run it as a daemon

**Comment by circuitdb** [comment]
Also can you try to run node-red standalone? You can find it in:
<your pimatic path>/node_modules/pimatic-node-red/node_modules/node-red/bin/

**Comment by thost96** [comment]
@circuitdb Here is the pimatic-daemon.log ouput: 

```
12:16:18.584 [pimatic] info: Loading plugin: "pimatic-node-red" (0.0.6)
12:16:18.844 [pimatic] error: Cannot find module 'i18next-client'
```

**Comment by thost96** [comment]
The directory `/node_modules/pimatic-node-red/node_modules/node-red/bin/` was empty. 
So i removed the node-red folder and installed it again via `sudo npm install node-red@0.14.6` and now it`s working fine. 

I would also be nice if you could update your readme with more information on how to access the node-red interface etc.
