### ISSUE TITLE
Set variables to pimatic

### ISSUE THREAD

**Issue by rikki78** [circuitdb/pimatic-node-red#6]
Hello,

Is it possible to add support to set variables from node red to pimatic? Or is that possible in a way already?

thanks

**Comment by joshendriks** [comment]
Not yet supported, but thanks for the request. I will try to add it soon!

**Comment by joshendriks** [comment]
Hi, I just added variable support. Please have a go at it and let me know if you encounter anything

**Comment by rikki78** [comment]
Hi
I'm having troubles installing the update. This is the output of npm-debug.log



144 info installOne node-red@0.14.6
145 verbose installOne of node-red to /home/pi/pimatic-app/node_modules/pimatic-node-red not in flight; installing
146 verbose correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
147 verbose lock using /root/.npm/_locks/node-red-04816a302444b987.lock for /home/pi/pimatic-app/node_modules/pimatic-node-red/node_modules/node-red
148 silly install write writing node-red 0.14.6 to /home/pi/pimatic-app/node_modules/pimatic-node-red/node_modules/node-red
149 verbose unbuild node_modules/pimatic-node-red/node_modules/node-red
150 silly gentlyRm /home/pi/pimatic-app/node_modules/pimatic-node-red/node_modules/node-red is being purged from base /home/pi/pimatic-app
151 verbose gentlyRm don't care about contents; nuking /home/pi/pimatic-app/node_modules/pimatic-node-red/node_modules/node-red
152 silly vacuum-fs Error: ENOTDIR: not a directory, lstat '/home/pi/pimatic-app/node_modules/pimatic-node-red/node_modules/node-red'
152 silly vacuum-fs     at Error (native)
153 verbose unlock done using /root/.npm/_locks/node-red-04816a302444b987.lock for /home/pi/pimatic-app/node_modules/pimatic-node-red/node_modules/node-red
154 verbose about to build /home/pi/pimatic-app/node_modules/pimatic-node-red
155 verbose unlock done using /root/.npm/_locks/pimatic-node-red-ac19c7cf109d38f8.lock for /home/pi/pimatic-app/node_modules/pimatic-node-red
156 verbose stack Error: ENOTDIR: not a directory, lstat '/home/pi/pimatic-app/node_modules/pimatic-node-red/node_modules/node-red'
156 verbose stack     at Error (native)
157 verbose cwd /home/pi/pimatic-app
158 error Linux 4.4.21-v7+
159 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pimatic-node-red"
160 error node v4.4.5
161 error npm  v2.15.5
162 error path /home/pi/pimatic-app/node_modules/pimatic-node-red/node_modules/node-red
163 error code ENOTDIR
164 error errno -20
165 error syscall lstat
166 error ENOTDIR: not a directory, lstat '/home/pi/pimatic-app/node_modules/pimatic-node-red/node_modules/node-red'
167 error If you need help, you may report this error at:
167 error     <https://github.com/npm/npm/issues>
168 verbose exit [ -20, true ]
169 verbose unbuild node_modules/pimatic-node-red/node_modules/node-red
170 silly gentlyRm /home/pi/pimatic-app/node_modules/pimatic-node-red/node_modules/node-red is being purged from base /home/pi/pimatic-app
171 verbose gentlyRm don't care about contents; nuking /home/pi/pimatic-app/node_modules/pimatic-node-red/node_modules/node-red
172 silly vacuum-fs Error: ENOTDIR: not a directory, lstat '/home/pi/pimatic-app/node_modules/pimatic-node-red/node_modules/node-red'
172 silly vacuum-fs     at Error (native)
173 error error rolling back Error: ENOTDIR: not a directory, lstat '/home/pi/pimatic-app/node_modules/pimatic-node-red/node_modules/node-red'
173 error error rolling back     at Error (native)
173 error error rolling back  { [Error: ENOTDIR: not a directory, lstat '/home/pi/pimatic-app/node_modules/pimatic-node-red/node_modules/node-red']
173 error error rolling back   errno: -20,
173 error error rolling back   code: 'ENOTDIR',
173 error error rolling back   syscall: 'lstat',
173 error error rolling back   path: '/home/pi/pimatic-app/node_modules/pimatic-node-red/node_modules/node-red' }

**Comment by joshendriks** [comment]
Somehow the node_modules symlink (that I use during dev) got into the package. version 0.0.8 should be ok now

**Comment by rikki78** [comment]
great thanks this did it! Works straight from the box.
By the way, I didn't have to re-install other nodes (like Bigtimer) either. In an earlier update I did have to.

**Comment by joshendriks** [comment]
Ok, thanks for the feedback!
I think reinstalling the other nodes is only required when node-red is updated. This release does not contain a new version of node-red. And one of the previous ones did.
