### ISSUE TITLE
Actions for devices

### ISSUE THREAD

**Issue by rikki78** [circuitdb/pimatic-node-red#8]
Where can I find the allowed actions on devices?
turnOn and turnOff are known but how can I set the presence of a device for example? Is there a list available?

**Comment by joshendriks** [comment]
This really depends on which actions are implemented by the specific device. Easiest to look into the coffe script source code of your device and find out which actions are implemented.

By the way: setting the precense is typically not something can do. As most sensors do not support actions at all. Can you explain a bit more? What are you trying to achieve?

**Comment by rikki78** [comment]
All right thanks! I'm trying to set the presence of a Dummy Presence sensor. I've found out can be done with the changePresenceTo action.
